// 📁 src/lib/tierData.ts
// Complete tier and business data for RISE OF A YN

export const TIERS = {
    1: {
      name: 'YN (Youngin\')',
      icon: '🧒',
      description: 'Learning the streets',
      minLevel: 1,
      maxLevel: 9,
      minXP: 0,
      maxXP: 2000,
      bossName: 'Neighborhood OG',
      bossIcon: '👴',
      powerRequired: 250,
      bossReward: { cash: 5000, xp: 500, respect: 50 },
    },
    2: {
      name: 'Trap (Block Boss)',
      icon: '🏚️',
      description: 'Running the block',
      minLevel: 10,
      maxLevel: 24,
      minXP: 2000,
      maxXP: 10000,
      bossName: 'Block Captain',
      bossIcon: '👨‍⚖️',
      powerRequired: 800,
      bossReward: { cash: 25000, xp: 2000, respect: 150 },
    },
    3: {
      name: 'Entrepreneur',
      icon: '💼',
      description: 'Going legit',
      minLevel: 25,
      maxLevel: 49,
      minXP: 10000,
      maxXP: 50000,
      bossName: 'City Controller',
      bossIcon: '🤵',
      powerRequired: 3000,
      bossReward: { cash: 100000, xp: 8000, respect: 400 },
    },
    4: {
      name: 'Boss',
      icon: '👑',
      description: 'Nationwide power',
      minLevel: 50,
      maxLevel: 79,
      minXP: 50000,
      maxXP: 200000,
      bossName: 'State Kingpin',
      bossIcon: '🎰',
      powerRequired: 10000,
      bossReward: { cash: 500000, xp: 40000, respect: 1500 },
    },
    5: {
      name: 'El Jefe',
      icon: '💎',
      description: 'Global dominance',
      minLevel: 80,
      maxLevel: 999,
      minXP: 200000,
      maxXP: Infinity,
      bossName: 'Global Don',
      bossIcon: '🌍',
      powerRequired: 50000,
      bossReward: { cash: 2000000, xp: 200000, respect: 5000 },
    },
  };
  
  export const BUSINESSES = {
    1: [ // Tier 1 - YN
      {
        id: 'water-boy',
        name: 'Water Boy Crew',
        icon: '💧',
        tier: 1,
        baseIncome: 50,
        baseCost: 1000,
        description: 'Sell water to the homies',
      },
      {
        id: 'boot-removal',
        name: 'Boot Removal',
        icon: '👢',
        tier: 1,
        baseIncome: 75,
        baseCost: 2500,
        description: 'Remove boots from cars',
      },
      {
        id: 'sneaker-flip',
        name: 'Sneaker Flip',
        icon: '👟',
        tier: 1,
        baseIncome: 100,
        baseCost: 5000,
        description: 'Buy and resell sneakers',
      },
      {
        id: 'studio-shares',
        name: 'Studio Shares',
        icon: '🎤',
        tier: 1,
        baseIncome: 150,
        baseCost: 10000,
        description: 'Rent studio time',
      },
    ],
    2: [ // Tier 2 - Trap
      {
        id: 'trap-house',
        name: 'Trap House',
        icon: '🏚️',
        tier: 2,
        baseIncome: 500,
        baseCost: 50000,
        description: 'Run a trap house',
      },
      {
        id: 'car-wash',
        name: 'Car Wash',
        icon: '🚗',
        tier: 2,
        baseIncome: 750,
        baseCost: 100000,
        description: 'Professional car wash',
      },
      {
        id: 'food-truck',
        name: 'Food Truck',
        icon: '🍔',
        tier: 2,
        baseIncome: 1000,
        baseCost: 150000,
        description: 'Mobile food operation',
      },
      {
        id: 'liquor-store',
        name: 'Liquor Store',
        icon: '🥃',
        tier: 2,
        baseIncome: 1500,
        baseCost: 250000,
        description: 'Corner liquor store',
      },
    ],
    3: [ // Tier 3 - Entrepreneur
      {
        id: 'car-dealership',
        name: 'Car Dealership',
        icon: '🏎️',
        tier: 3,
        baseIncome: 5000,
        baseCost: 500000,
        description: 'Sell luxury cars',
      },
      {
        id: 'real-estate',
        name: 'Real Estate',
        icon: '🏢',
        tier: 3,
        baseIncome: 7500,
        baseCost: 1000000,
        description: 'Property rentals',
      },
      {
        id: 'nightclub',
        name: 'Nightclub',
        icon: '🍾',
        tier: 3,
        baseIncome: 10000,
        baseCost: 2500000,
        description: 'VIP nightclub',
      },
      {
        id: 'record-label',
        name: 'Record Label',
        icon: '💿',
        tier: 3,
        baseIncome: 15000,
        baseCost: 5000000,
        description: 'Music production',
      },
    ],
    4: [ // Tier 4 - Boss
      {
        id: 'import-co',
        name: 'Import Co.',
        icon: '📦',
        tier: 4,
        baseIncome: 50000,
        baseCost: 10000000,
        description: 'International imports',
      },
      {
        id: 'logistics',
        name: 'Logistics Fleet',
        icon: '🚚',
        tier: 4,
        baseIncome: 75000,
        baseCost: 25000000,
        description: 'Shipping operations',
      },
      {
        id: 'jet-lease',
        name: 'Jet Lease',
        icon: '✈️',
        tier: 4,
        baseIncome: 100000,
        baseCost: 50000000,
        description: 'Private jet leasing',
      },
      {
        id: 'tech-startup',
        name: 'Tech Startup',
        icon: '💻',
        tier: 4,
        baseIncome: 150000,
        baseCost: 100000000,
        description: 'Tech company',
      },
    ],
    5: [ // Tier 5 - El Jefe
      {
        id: 'oil-field',
        name: 'Oil Field',
        icon: '🛢️',
        tier: 5,
        baseIncome: 500000,
        baseCost: 500000000,
        description: 'Oil production',
      },
      {
        id: 'wind-farm',
        name: 'Wind Farm',
        icon: '💨',
        tier: 5,
        baseIncome: 750000,
        baseCost: 1000000000,
        description: 'Renewable energy',
      },
      {
        id: 'cruise-line',
        name: 'Cruise Line',
        icon: '⛴️',
        tier: 5,
        baseIncome: 1000000,
        baseCost: 2500000000,
        description: 'Luxury cruises',
      },
      {
        id: 'overseas-port',
        name: 'Overseas Port',
        icon: '🌊',
        tier: 5,
        baseIncome: 2000000,
        baseCost: 5000000000,
        description: 'International port',
      },
    ],
  };
  
  export const ASSETS = {
    homes: [
      // Tier 1
      { id: 'trap-room', tier: 1, name: 'Trap Room', icon: '🛏️', price: 5000 },
      { id: 'basement', tier: 1, name: 'Studio Basement', icon: '🏚️', price: 10000 },
      { id: 'apartment', tier: 1, name: 'Shared Apartment', icon: '🏠', price: 15000 },
      { id: 'backhouse', tier: 1, name: 'Back-House', icon: '🏘️', price: 25000 },
      { id: 'duplex-1', tier: 1, name: 'Duplex', icon: '🏘️', price: 50000 },
      
      // Tier 2
      { id: 'loft', tier: 2, name: 'Garage Loft', icon: '🏢', price: 100000 },
      { id: 'house', tier: 2, name: 'One-Story Home', icon: '🏠', price: 200000 },
      { id: 'townhouse', tier: 2, name: 'Townhouse', icon: '🏘️', price: 350000 },
      { id: 'duplex-2', tier: 2, name: 'Duplex', icon: '🏘️', price: 500000 },
      { id: 'complex', tier: 2, name: '2-Unit Complex', icon: '🏢', price: 750000 },
      
      // Tier 3
      { id: 'suburban', tier: 3, name: 'Suburban Home', icon: '🏡', price: 1000000 },
      { id: 'lake-house', tier: 3, name: 'Lake House', icon: '🏞️', price: 2500000 },
      { id: 'condo', tier: 3, name: 'Condo', icon: '🏢', price: 3500000 },
      { id: 'estate-3', tier: 3, name: 'Mini Estate', icon: '👑', price: 5000000 },
      
      // Tier 4
      { id: 'mansion', tier: 4, name: 'Mansion', icon: '🏰', price: 10000000 },
      { id: 'penthouse', tier: 4, name: 'Penthouse', icon: '🌇', price: 25000000 },
      { id: 'estate-4', tier: 4, name: 'Estate', icon: '👑', price: 50000000 },
      { id: 'beach-villa', tier: 4, name: 'Beach Villa', icon: '🏝️', price: 75000000 },
      
      // Tier 5
      { id: 'mega-estate', tier: 5, name: 'Mega Estate', icon: '🏰', price: 500000000 },
      { id: 'island-villa', tier: 5, name: 'Island Villa', icon: '🏝️', price: 1000000000 },
      { id: 'compound', tier: 5, name: 'Desert Compound', icon: '🏜️', price: 2500000000 },
    ],
    cars: [
      // Tier 1
      { id: 'bike', tier: 1, name: 'Bike', icon: '🏍️', price: 2000 },
      { id: 'crown-vic', tier: 1, name: 'Crown Vic', icon: '🚗', price: 5000 },
      { id: 'civic', tier: 1, name: 'Civic', icon: '🚗', price: 8000 },
      { id: 'impala', tier: 1, name: 'Old Impala', icon: '🚙', price: 12000 },
      { id: 'charger-se', tier: 1, name: 'Charger SE', icon: '🏎️', price: 20000 },
      
      // Tier 2
      { id: 'altima', tier: 2, name: 'Altima', icon: '🚗', price: 50000 },
      { id: 'camaro', tier: 2, name: 'Camaro', icon: '🏎️', price: 75000 },
      { id: 'charger-rt', tier: 2, name: 'Charger RT', icon: '🏎️', price: 100000 },
      { id: 'accord', tier: 2, name: 'Accord Sport', icon: '🚗', price: 120000 },
      { id: 'tahoe', tier: 2, name: 'Tahoe LT', icon: '🚙', price: 150000 },
      
      // Tier 3
      { id: 'bmw', tier: 3, name: 'BMW M3', icon: '🏎️', price: 500000 },
      { id: 'tesla', tier: 3, name: 'Tesla S', icon: '🚗', price: 750000 },
      { id: 'mercedes', tier: 3, name: 'Mercedes C63', icon: '🏎️', price: 1000000 },
      { id: 'audi', tier: 3, name: 'Audi RS5', icon: '🏎️', price: 1250000 },
      { id: 'lexus', tier: 3, name: 'Lexus IS 350', icon: '🚗', price: 1500000 },
      
      // Tier 4
      { id: 'lambo', tier: 4, name: 'Lambo Huracán', icon: '🏎️', price: 5000000 },
      { id: 'mclaren', tier: 4, name: 'McLaren 720S', icon: '🏎️', price: 7500000 },
      { id: 'gwagon', tier: 4, name: 'G-Wagon', icon: '🚙', price: 10000000 },
      { id: 'range', tier: 4, name: 'Range SVR', icon: '🚙', price: 12500000 },
      { id: 'amg', tier: 4, name: 'AMG GT', icon: '🏎️', price: 15000000 },
      
      // Tier 5
      { id: 'rolls', tier: 5, name: 'Rolls Royce', icon: '👑', price: 100000000 },
      { id: 'bugatti', tier: 5, name: 'Bugatti', icon: '🏎️', price: 250000000 },
      { id: 'ferrari', tier: 5, name: 'Ferrari SF90', icon: '🏎️', price: 500000000 },
      { id: 'yacht', tier: 5, name: 'Super Yacht', icon: '⛵', price: 1000000000 },
    ],
  };
  
  export const HUSTLES = {
    1: [ // Tier 1
      { id: 'hustle-1', name: 'Grind It', icon: '💪', reward: 100, xp: 5, energy: 10 },
      { id: 'hustle-2', name: 'Hustle Hard', icon: '🔥', reward: 200, xp: 10, energy: 20 },
      { id: 'hustle-3', name: 'Go All In', icon: '💯', reward: 500, xp: 25, energy: 50 },
    ],
    2: [ // Tier 2
      { id: 'hustle-1', name: 'Street Work', icon: '🚗', reward: 1000, xp: 50, energy: 10 },
      { id: 'hustle-2', name: 'Trap Grind', icon: '📦', reward: 2500, xp: 100, energy: 20 },
      { id: 'hustle-3', name: 'Go Hard', icon: '💪', reward: 5000, xp: 250, energy: 50 },
    ],
    3: [ // Tier 3
      { id: 'hustle-1', name: 'Business Deal', icon: '💼', reward: 10000, xp: 500, energy: 10 },
      { id: 'hustle-2', name: 'Major Play', icon: '💰', reward: 25000, xp: 1000, energy: 20 },
      { id: 'hustle-3', name: 'Big Move', icon: '🎯', reward: 50000, xp: 2500, energy: 50 },
    ],
    4: [ // Tier 4
      { id: 'hustle-1', name: 'Corporation Deal', icon: '🏢', reward: 100000, xp: 5000, energy: 10 },
      { id: 'hustle-2', name: 'National Play', icon: '🌎', reward: 250000, xp: 10000, energy: 20 },
      { id: 'hustle-3', name: 'Empire Move', icon: '👑', reward: 500000, xp: 25000, energy: 50 },
    ],
    5: [ // Tier 5
      { id: 'hustle-1', name: 'Global Deal', icon: '🌍', reward: 1000000, xp: 50000, energy: 10 },
      { id: 'hustle-2', name: 'World Power', icon: '💎', reward: 2500000, xp: 100000, energy: 20 },
      { id: 'hustle-3', name: 'Dominance', icon: '👑', reward: 5000000, xp: 250000, energy: 50 },
    ],
  };